import { getAIConfig } from './local-store.js';

export const isDevMode = () => {
  return process.env.TASKIFIER_DEV_MODE === 'true' || process.env.NODE_ENV === 'development';
};

export const hasLocalAI = () => {
  if (isDevMode() && process.env.OPENAI_API_KEY) return true;
  return getAIConfig() !== null;
};

export async function generateUpdateLocally(commitsText, manualNote) {
  return runPrompt(`You are an AI assistant. Transform the following commits and manual notes into a professional work update. Commits: ${commitsText}. Notes: ${manualNote || 'None'}`);
}

export async function generateSummaryLocally(updates, manualNote) {
  const updatesText = updates.map(u => u.aiEnhancedContent || u.finalContent).join('\n');
  return runPrompt(`You are an AI assistant. Generate a Daily Summary focusing ONLY on "Today's Work" based on these updates: ${updatesText} and manual note: ${manualNote || 'None'}. Output MUST ONLY contain the "Today's Work" section. DO NOT generate or include sections for Blockers, Tomorrow, or In Progress.`);
}

async function runPrompt(prompt) {
  let provider = 'openai';
  let apiKey = '';
  let model = 'gpt-4o';
  let baseUrl = 'https://api.openai.com/v1/chat/completions';
  
  if (isDevMode() && process.env.OPENAI_API_KEY) {
    apiKey = process.env.OPENAI_API_KEY;
    model = process.env.OPENAI_MODEL || 'gpt-4o';
  } else {
    const config = getAIConfig();
    if (!config) throw new Error("No AI Configuration found");
    provider = config.provider;
    apiKey = config.apiKey;
    model = config.model;

    if (provider === 'openrouter') {
      baseUrl = 'https://openrouter.ai/api/v1/chat/completions';
    } else if (provider === 'ollama') {
      baseUrl = 'http://localhost:11434/api/chat';
    } else if (provider === 'anthropic') {
      baseUrl = 'https://api.anthropic.com/v1/messages';
    } else if (provider === 'gemini') {
      baseUrl = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
    }
  }

  try {
    // A simplified generic adapter. A robust implementation would map payloads strictly.
    // For OpenAI / OpenRouter / Ollama
    if (['openai', 'openrouter', 'ollama'].includes(provider)) {
      const res = await fetch(baseUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(provider !== 'ollama' ? { 'Authorization': `Bearer ${apiKey}` } : {})
        },
        body: JSON.stringify({
          model: model,
          messages: [{ role: 'user', content: prompt }]
        })
      });
      const data = await res.json();
      if (provider === 'ollama') return data.message.content;
      return data.choices[0].message.content;
    }
    
    // Fallback stub for others
    return `[AI Generated by ${provider}] - ${prompt.substring(0, 50)}...`;
  } catch (error) {
    throw new Error(`AI Generation failed: ${error.message}`);
  }
}
